config/routes.rb
Rails.application.routes.draw do
  resources :nodes do
    resources :log_lines
  end
  resources :logs

  root 'nodes#index'
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :log_lines
  default_scope -> { order(:name) }

  alias_attribute :to_s, :name
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_nodes
  before_action :set_node, only: [:show, :edit, :update, :destroy]
  INCLUDES = %i()

  respond_to :html, :js, :datatable

  def index
    respond_with @nodes do |format|
      format.datatable do
        render json: NodesDatatable.new(view_context, collection: @nodes)
      end
    end
  end

  def show
    respond_with @node
  end

  def new
    @node = Node.new
    add_breadcrumb :new
    respond_with @node
  end

  def edit
    add_breadcrumb :edit
  end

  def create
    @node = Node.new node_params
    @node.save
    respond_with(@node)
  end

  def update
    @node.update node_params
    respond_with @node
  end

  def destroy
    @node.destroy
    respond_with @node
  end

  private

  def set_nodes
    @nodes = Node.includes(INCLUDES).references(INCLUDES)
    add_breadcrumb :index, :nodes_path
  end

  def set_node
    @node = @nodes.find params[:id]
    add_breadcrumb @node, @node
  end

  def node_params
    permitted = %i(comment priority)
    params.require(:node).permit permitted
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.haml
= bootstrap_form_for @node do |f|
  = f.alert_message t 'errors.template.body'

  = f.static_control :name

  = f.form_group do
    = f.primary
    = cancel_link

app/views/nodes/edit.html.haml
- model_class = Node
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/nodes/index.html.haml
- model_class = Node
- model_names = (0..2).collect {|i| model_class.model_name.human(count: i).downcase }
.page-header
  %h1
    =t '.title', default: model_class.model_name.human.pluralize.titleize
    = new_crud_btn(model_class)

%table.table.table-striped{ data: { source: url_for([model_class, format: 'datatable']), resourcenames: model_names } }
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:updated_at)
      %th.actions{ data: { orderable: 'false' } }=t '.actions', default: t("helpers.actions")
  %tbody

app/views/nodes/new.html.haml
- model_class = Node
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/nodes/show.html.haml
- model_class = Node
%div.page-header
  %h1
    = t '.title', default: model_class.model_name.human.titleize
    "#{@node.name}"
    .pull-right
      = link_to node_log_lines_path(@node), class: 'btn btn-link' do
        = fa_icon 'list-ol', text:  t('activerecord.model.log_line.other')
      = action_btns @node

%fieldset.tab
  %ul.nav.nav-tabs{ role: 'tablist' }
    %li.active{ role: 'presentation' }
      = link_to 'Info', '#info', role: 'tab', data: { toggle: 'tab' }, aria: { controls: 'info'}
    %li{ role: 'presentation'}
      = link_to '#log-lines', role: 'tab', data: { toggle: 'tab' }, aria: { controls: 'log-lines'} do
        = t('activerecord.model.log_line.other')
        = bs_badge @node.log_lines.count

  .tab-content
    .tab-pane.fade.in.active#info{role: 'tabpanel'}
      %dl
        = label_with_value model_class.human_attribute_name(:created_at), timestamp(@node.created_at)
        = label_with_value model_class.human_attribute_name(:updated_at), timestamp(@node.updated_at)

    .tab-pane.fade#log-lines{role: 'tabpanel' }
      = render partial: 'log_lines/log_lines_table'